version: '3'
services:
  api:
    build:
      context: API
      dockerfile: Dockerfile
    image: node
    container_name: bta-reg-api
    restart: unless-stopped
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - bta-reg-network
    command: npm start
  web:
    build:
      context: Client
      dockerfile: Dockerfile.prod
    image: nginx:stable-alpine
    container_name: bta-reg-web
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - bta-reg-network
    command: nginx -g "daemon off;"
networks:
  bta-reg-network:
    driver: bridge